model:
  arch: blip_vqa

  model_type: vqav2
  load_finetuned: False

  image_size: 480

datasets:
  coco_vqa: # name of the dataset builder
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 480
        eval:
          name: "blip_image_eval"
          image_size: 480
    text_processor:
        train:
          name: "blip_question"
        eval:
          name: "blip_question"

run:
  task: vqa
  # optimization-specific
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 2e-5
  min_lr: 0
  weight_decay: 0.05
  batch_size_train: 16
  batch_size_eval: 64
  num_workers: 8

  # inference-specific
  max_len: 10
  min_len: 1
  num_beams: 3
  num_ans_candidates: 128
  inference_method: "rank"

  log_freq: 2000
  max_epoch: 5
  
  seed: 42
  output_dir: "output/original/blip/vqa"

  amp: False
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]
  valid_splits: []
  test_splits: ["test"]

  # distribution-specific
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
